In [1]:
import numpy as np

In [2]:
def solve (dimension,value):
    return np.full(dimension,value)

In [3]:
solve((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

# we can create without creating any func


In [5]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [10]:
def xyz (dimension,value):
    return np.full(dimension,value)

In [11]:
xyz((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

# showing elements of array

In [31]:
arr=np.array([1,3,5,7])
for i in arr:
    print(i)

1
3
5
7


# 1.[234] 2.[455] 3.[567]-add array

In [12]:
def sum_coeff(array):
    result=np.zeros(len(array[0]))
    for arr in array:
        result+=arr
    return result

In [15]:
sum_coeff([np.array([1,4,7]),np.array([1,4,6]),np.array([1,4,8])])

array([ 3., 12., 21.])

In [16]:
np.zeros((1,3))

array([[0., 0., 0.]])

# addition of 2 list

In [22]:
test1 = [1, 3, 4, 6, 8] 
test2 = [4, 5, 6, 2, 10] 
  

  
  
res_list = [] 
for i in range(0, len(test1)): 
    res_list.append(test1[i] + test2[i]) 
  

print ("sum is is : " + str(res_list)) 

sum is is : [5, 8, 10, 8, 18]


# without using function add 2 array

In [25]:
arr1 = np.array([2, -7, 5]) 
arr2 = np.array([5, 8, -5]) 
   
print ("1st Input array : ", arr1)  
print ("2nd Input array : ", arr2)  
    
out_arr = np.add(arr1, arr2)  
print ("output added array : ", out_arr)  

1st Input array :  [ 2 -7  5]
2nd Input array :  [ 5  8 -5]
output added array :  [7 1 0]


# Give a 2D array NXM dim ,write a function which will accept array and 2 number N,M and return the top left sub- matrix

In [50]:
def top_left_sub(matrix,n,m):
    return matrix[:n, :m]
#create 3*3 matrix
matrix=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(matrix)
top_left_sub(matrix,2,2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2],
       [4, 5]])

### to print bottom right 2 sub matrix

In [52]:
def top_left_sub(matrix,n,m):
    return matrix[n:, m:]

matrix=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(matrix)
top_left_sub(matrix,1,1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[5, 6],
       [8, 9]])

# give 1D array write a function accept array as parameter .function should return dictionary with mean and std. deviation

In [54]:
def sol(arr):
    return {'mean':arr.mean(),'std_dev':arr.std()}

sol(np.array([1,2,3]))


{'mean': 2.0, 'std_dev': 0.816496580927726}