In [10]:
import numpy as np
import sys
import time
import scipy

In [5]:
!pip3 install pandas

    100% |████████████████████████████████| 10.0MB 113kB/s ta 0:00:011   10% |███▎                            | 1.0MB 24.5MB/s eta 0:00:01    71% |██████████████████████▉         | 7.2MB 2.3MB/s eta 0:00:02
    100% |████████████████████████████████| 512kB 949kB/s ta 0:00:011    60% |███████████████████▎            | 307kB 11.7MB/s eta 0:00:01
    100% |████████████████████████████████| 20.2MB 51kB/s eta 0:00:011
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl


In [9]:
!pip3 install scipy

    100% |████████████████████████████████| 26.1MB 27kB/s  eta 0:00:01    79% |█████████████████████████▍      | 20.6MB 8.2MB/s eta 0:00:01    84% |███████████████████████████     | 22.1MB 3.6MB/s eta 0:00:02
  Using cached https://files.pythonhosted.org/packages/3d/fc/4763e5f17ac6e7e7d55f377cde859ca1c5d5ac624441ab45315bc578aa9e/numpy-1.18.3-cp36-cp36m-manylinux1_x86_64.whl


In [4]:
import pandas as pd

In [5]:
a=np.array([1,2,3])

In [6]:
a

array([1, 2, 3])

In [9]:
b=np.array([[2,3,4],[3,4,5]])

In [10]:
b

array([[2, 3, 4],
       [3, 4, 5]])

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [24]:
np.linspace(5,6,5)

array([5.  , 5.25, 5.5 , 5.75, 6.  ])

In [22]:
np.random.rand(3,2)

array([[0.48018655, 0.2508151 ],
       [0.62343684, 0.45262623],
       [0.03159028, 0.26014148]])

In [25]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [60]:
a=np.array([[25,6,7],[3,4,5]])

a.shape

(2, 3)

In [61]:
a.shape=(3,2)
a

array([[25,  6],
       [ 7,  3],
       [ 4,  5]])

In [34]:
a.shape=(6,1)
a

array([[25],
       [ 6],
       [ 7],
       [ 3],
       [ 4],
       [ 5]])

In [36]:
b=np.arange(25)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
b.size

25

In [40]:
a=np.arange(10,dtype=float)
print(a.dtype)
a

float64


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [52]:
np.sum([[1,2],[6,3]])

12

In [53]:
np.sum([[1,2],[6,3]],axis=0)

array([7, 5])

In [54]:
np.sum([[1,2],[2,3]],axis=1)

array([3, 5])

In [64]:
l=range(1000)

In [69]:
l

range(0, 1000)

In [70]:
print('size of list:',sys.getsizeof(1)*len(l))

size of list: 28000


In [79]:
def using_list():
    t1=time.time()
    X=range(100000)
    Y=range(100000)
    Z=[X[i]+Y[i] for i in range(len(X))]
    return time.time()-t1
def using_Numpy():
    t1=time.time()
    a=np.arange(100000)
    b=np.arange(100000)
    Z=a+b
    return time.time()-t1

list_time=using_list()
print('python:',list_time)

numpy_time=using_Numpy()
print('Numpy:',numpy_time)



python: 0.07254719734191895
Numpy: 0.004233360290527344


In [1]:
pwd

'/home/kumarmai'

In [ ]:
cd /home/kumarmai/Down